### ISSUE TITLE
Can't do computations with Distributed for zarr based YAXArray

### ISSUE THREAD

**Issue by felixcremer** [meggart/YAXArrays.jl#16] opened 2020-08-27 11:25 UTC
When I try to make a compuation using Distributed with a few workers, the code seems to hang and if I interrupt it after a few minutes I get the following error:

```julia
julia> savecube(t, "/home/crem_fe/Daten/esdl_gdal/test_jurua_dist_true.nc", backend=:netcdf, overwrite=true)
persist = true
^CERROR: InterruptException:
Stacktrace:
 [1] try_yieldto(::typeof(Base.ensure_rescheduled)) at ./task.jl:656
 [2] wait at ./task.jl:713 [inlined]
 [3] wait(::Base.GenericCondition{ReentrantLock}) at ./condition.jl:106
 [4] take_buffered(::Channel{Any}) at ./channels.jl:387
 [5] take!(::Channel{Any}) at ./channels.jl:381
 [6] take!(::Distributed.RemoteValue) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:599
 [7] take_ref(::Distributed.RRID, ::Int64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:610
 [8] call_on_owner at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:492 [inlined]
 [9] take!(::RemoteChannel{Channel{Any}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:626
 [10] runLoop(::YAXArrays.DAT.DATConfig{1,1}, ::Bool) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:406
 [11] mapCube(::YAXArrays.DAT.var"#cop#256", ::Tuple{YAXArray{Union{Missing, Float32},3,Zarr.ZArray{Union{Missing, Float32},3,Zarr.BloscCompressor,Zarr.DirectoryStore},Array{RangeAxis,1}}}; max_cache::Float64, indims::InDims, outdims::OutDims, inplace::Bool, ispar::Bool, debug::Bool, include_loopvars::Bool, showprog::Bool, nthreads::Dict{Int64,Int64}, loopchunksize::Dict{Any,Any}, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:278
 [12] #mapCube#34 at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:177 [inlined]
 [13] savecube(::YAXArray{Union{Missing, Float32},3,Zarr.ZArray{Union{Missing, Float32},3,Zarr.BloscCompressor,Zarr.DirectoryStore},Array{RangeAxis,1}}, ::String; chunksize::Dict{Any,Any}, max_cache::Float64, backend::Symbol, backendargs::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:overwrite,),Tuple{Bool}}}) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/CubeIO.jl:39
 [14] top-level scope at REPL[10]:1
 [15] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```

**Comment by meggart** [comment] 2020-08-28 07:37
This is netcdf backend? Then the code should actually run on a single process only, because you can not write concurrently to the same file. I will test this. Does it work when you set `backend=:zarr`

**Comment by felixcremer** [comment] 2020-08-28 09:34
Sorry, I copied the wrong error message, this also happens for zarr cubes and it also happens for normal computations. 
The tslength function takes the number of non-missing values per pixel and it is done for a small example in a few seconds but it hangs for the distributed case. 
I added a very small example testfile for which this already fails for me. 

[envistack.zarr.zip](https://github.com/meggart/YAXArrays.jl/files/5141285/envistack.zarr.zip)

```julia
julia> ts = ESDLHelpers.tslength(t)
persist = false
^CERROR: InterruptException:
Stacktrace:
 [1] poptask(::Base.InvasiveLinkedListSynchronized{Task}) at ./task.jl:704
 [2] wait at ./task.jl:712 [inlined]
 [3] wait(::Base.GenericCondition{ReentrantLock}) at ./condition.jl:106
 [4] take_buffered(::Channel{Any}) at ./channels.jl:387
 [5] take!(::Channel{Any}) at ./channels.jl:381
 [6] take!(::Distributed.RemoteValue) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:599
 [7] take_ref(::Distributed.RRID, ::Int64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:610
 [8] call_on_owner at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:492 [inlined]
 [9] take!(::RemoteChannel{Channel{Any}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:626
 [10] runLoop(::YAXArrays.DAT.DATConfig{1,1}, ::Bool) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:406
 [11] mapCube(::typeof(ESDLHelpers.ctslength), ::Tuple{YAXArray{Union{Missing, Float32},3,Zarr.ZArray{Union{Missing, Float32},3,Zarr.BloscCompressor,Zarr.DirectoryStore},Array{CubeAxis,1}}}; max_cache::Float64, indims::InDims, outdims::OutDims, inplace::Bool, ispar::Bool, debug::Bool, include_loopvars::Bool, showprog::Bool, nthreads::Dict{Int64,Int64}, loopchunksize::Dict{Any,Any}, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:278
 [12] #mapCube#34 at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:177 [inlined]
 [13] #mapslices#48 at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:217 [inlined]
 [14] tslength(::YAXArray{Union{Missing, Float32},3,Zarr.ZArray{Union{Missing, Float32},3,Zarr.BloscCompressor,Zarr.DirectoryStore},Array{CubeAxis,1}}) at /home/crem_fe/.julia/dev/ESDLHelpers/src/tsanalysis.jl:115
 [15] top-level scope at REPL[19]:1
 [16] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```

**Comment by meggart** [comment] 2020-08-28 14:43
I really can not reproduce this. Loading your data and processing parallel seems to work:

````julia
julia> envi = Cube("/home/fgans/Downloads/envistack.zarr")
YAXArray with the following dimensions
Y                   Axis with 10 Elements from -98.6335185299432 to -98.63190156243179
X                   Axis with 10 Elements from 20.6311005446814 to 20.629483577169985
Band                Axis with 271 elements: Band_1 Band_2 .. Band_270 Band_271 
Total size: 105.86 KB


julia> r = mapslices(sum,envi,dims=("X","Y"))
persist = false
      From worker 2:    Error during running loop: RemoteException(1, CapturedException(InvalidStateException("Channel is closed.", :closed), Any[(try_yieldto at task.jl:656, 1), (wait at task.jl:713 [inlined], 1), (wait at condition.jl:106, 1), (take_buffered at channels.jl:387, 1), (take! at channels.jl:381, 1), (take! at remotecall.jl:599, 1), (take_ref at remotecall.jl:610, 1), (#106 at process_messages.jl:294, 1), (run_work_thunk at process_messages.jl:79, 1), (macro expansion at process_messages.jl:294 [inlined], 1), (#105 at task.jl:356, 1)]))YAXArray
 with the following dimensions
Band                Axis with 271 elements: Band_1      From worker 3:  Error during running loop: RemoteException(1, CapturedException(InvalidStateException("Channel is closed.", :closed), Any[(try_yieldto at task.jl:656, 1), (wait at task.jl:713 [inlined], 1), (wait at condition.jl:106, 1), (take_buffered at channels.jl:387, 1), (take! at channels.jl:381, 1), (take! at remotecall.jl:599, 1), (take_ref at remotecall.jl:610, 1), (#106 at process_messages.jl:294, 1), (run_work_thunk at process_messages.jl:79, 1), (macro expansion at process_messages.jl:294 [inlined], 1), (#105 at task.jl:356, 1)])) 
Band_2 .. Band_270 Band_271 
Total size: 1.06 KB


julia> nprocs()
3

julia> r.data
ZArray{Union{Missing, Float32}} of size 271
````

There are new warnings in julia 1.5, but you can safely ignore them, I will take care of them soon, but the results are ok for me.

**Comment by felixcremer** [comment] 2020-08-31 13:05
I rechecked, that I am on the latest YAXArrays version and I made an even simpler example:
```julia
julia> using YAXArrays

julia> arr = rand(300,200,90)
julia> x = RangeAxis(:X, 1:300)
X                   Axis with 300 Elements from 1 to 300

julia> y = RangeAxis(:Y, 1:200)
Y                   Axis with 200 Elements from 1 to 200

julia> t = RangeAxis(:time, 1:90)
time                Axis with 90 Elements from 1 to 90

julia> yax = YAXArray([x,y,t], arr)
```

When I do it without multiple workers it works 
```julia
julia> @time mapslices(sum, yax, dims="time")
  8.299152 seconds (22.89 M allocations: 1.259 GiB, 4.27% gc time)
YAXArray with the following dimensions
X                   Axis with 300 Elements from 1 to 300
Y                   Axis with 200 Elements from 1 to 200
Total size: 468.75 KB


julia> @time mapslices(sum, yax, dims="time")
  0.098155 seconds (300.26 k allocations: 88.037 MiB, 15.49% gc time)
YAXArray with the following dimensions
X                   Axis with 300 Elements from 1 to 300
Y                   Axis with 200 Elements from 1 to 200
Total size: 468.75 KB
```
And when I add multiple workers like that it seems to hang and I canceld it after a minute because there are also no computations happening at least according to htop.

```julia
julia> using Zarr

julia> using Distributed

julia> addprocs(2)
2-element Array{Int64,1}:
 2
 3

julia> @time mapslices(sum, yax, dims="time")
persist = false
^CERROR: InterruptException:
Stacktrace:
 [1] poptask(::Base.InvasiveLinkedListSynchronized{Task}) at ./task.jl:704
 [2] wait at ./task.jl:712 [inlined]
 [3] wait(::Base.GenericCondition{ReentrantLock}) at ./condition.jl:106
 [4] take_buffered(::Channel{Any}) at ./channels.jl:387
 [5] take!(::Channel{Any}) at ./channels.jl:381
 [6] take!(::Distributed.RemoteValue) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:599
 [7] take_ref(::Distributed.RRID, ::Int64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:610
 [8] call_on_owner at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:492 [inlined]
 [9] take!(::RemoteChannel{Channel{Any}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:626
 [10] runLoop(::YAXArrays.DAT.DATConfig{1,1}, ::Bool) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:406
 [11] mapCube(::typeof(sum), ::Tuple{YAXArray{Float64,3,Array{Float64,3},Array{RangeAxis{Int64,S,UnitRange{Int64}} where S,1}}}; max_cache::Float64, indims::InDims, outdims::OutDims, inplace::Bool, ispar::Bool, debug::Bool, include_loopvars::Bool, showprog::Bool, nthreads::Dict{Int64,Int64}, loopchunksize::Dict{Any,Any}, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:278
 [12] #mapCube#34 at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:177 [inlined]
 [13] #mapslices#48 at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:217 [inlined]
 [14] top-level scope at ./timing.jl:174 [inlined]
 [15] top-level scope at ./REPL[14]:0
```

This is with the following versioninfo:
```julia
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 2
```
and the following package versions:

```julia
(YAXArrays) pkg> st
Project YAXArrays v1.0.0
Status `~/.julia/dev/YAXArrays/Project.toml`
  [179af706] CFTime v0.1.0
  [861a8166] Combinatorics v1.0.2
  [a93c6f00] DataFrames v0.21.7
  [864edb3b] DataStructures v0.17.20
  [fcd2136c] DiskArrayTools v0.1.0
  [3c3547ce] DiskArrays v0.2.4
  [7a1cc6ca] FFTW v1.2.4
  [c27321d9] Glob v1.3.0
  [a98d9a8b] Interpolations v0.12.10
  [8197267c] IntervalSets v0.5.1
  [c8e1da08] IterTools v1.3.0
  [a15396b6] OnlineStats v1.5.3
  [f27b6e38] Polynomials v1.1.6
  [92933f4c] ProgressMeter v1.3.2
  [ae029012] Requires v1.0.2
  [2913bbd2] StatsBase v0.33.1
  [bd369af6] Tables v1.0.5
  [bbac0a1f] WeightedOnlineStats v0.5.0
  [90b8fcef] YAXArrayBase v0.2.1
  [0a941bbe] Zarr v0.4.5
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [d6f4376e] Markdown
  [10745b16] Statistics
```

**Comment by meggart** [comment] 2020-08-31 14:40
Thanks a lot, finally I could reproduce it. The missing piece was `@everywhere using Zarr`, the output format could not be deserialized on the worker which led to an un-caught error and infinite waiting on a channel. I have fixed this and will push later when I have also fixed the printing of the remote exception that is still happening. So the following code should work:

````julia
using YAXArrays

arr = rand(300,200,90)
x = RangeAxis(:X, 1:300)
y = RangeAxis(:Y, 1:200)

t = RangeAxis(:time, 1:90)

yax = YAXArray([x,y,t], arr)

@time mapslices(sum, yax, dims="time")

@time mapslices(sum, yax, dims="time")

using Distributed

addprocs(2)

@everywhere using Zarr, YAXArrays

@time mapslices(sum, yax, dims="time")
````

**Comment by meggart** [comment] 2020-09-02 08:38
Can I close this? The code here at least throws an error on latest master...

**Comment by felixcremer** [comment] 2020-09-02 10:07
I have seen that it should catch that the YAXArrays package is not loaded everwhere, but when I run the code as above I get the following very long and for users confusing error message. I don't understand how this is happening, because when I run the lines 395 to 396 separately this works as expected. 

```julia
julia> @time mapslices(sum, yax, dims="time")
persist = false
ERROR: On worker 2:
KeyError: key YAXArrays [c21b50f5-aa40-41ea-b809-c0f5e47bfa5c] not found
getindex at ./dict.jl:467 [inlined]
root_module at ./loading.jl:968 [inlined]
deserialize_module at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:953
handle_deserialize at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:855
deserialize at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773
deserialize_datatype at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:1251
handle_deserialize at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:826
deserialize at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773
handle_deserialize at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:833
deserialize at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773 [inlined]
deserialize_msg at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/messages.jl:99
#invokelatest#1 at ./essentials.jl:710 [inlined]
invokelatest at ./essentials.jl:709 [inlined]
message_handler_loop at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:185
process_tcp_streams at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:142
#99 at ./task.jl:356
Stacktrace:
 [1] #remotecall_fetch#143 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:394 [inlined]
 [2] remotecall_fetch(::Function, ::Distributed.Worker, ::Distributed.RRID) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:386
 [3] #remotecall_fetch#146 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:421 [inlined]
 [4] remotecall_fetch at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:421 [inlined]
 [5] call_on_owner at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:494 [inlined]
 [6] fetch(::Future) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:533
 [7] _broadcast_getindex_evalf at ./broadcast.jl:648 [inlined]
 [8] _broadcast_getindex at ./broadcast.jl:621 [inlined]
 [9] getindex at ./broadcast.jl:575 [inlined]
 [10] copy at ./broadcast.jl:876 [inlined]
 [11] materialize at ./broadcast.jl:837 [inlined]
 [12] runLoop(::YAXArrays.DAT.DATConfig{1,1}, ::Bool) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:394
 [13] mapCube(::typeof(sum), ::Tuple{YAXArray{Float64,3,Array{Float64,3},Array{RangeAxis{Int64,S,UnitRange{Int64}} where S,1}}}; max_cache::Float64, indims::InDims, outdims::OutDims, inplace::Bool, ispar::Bool, debug::Bool, include_loopvars::Bool, showprog::Bool, nthreads::Dict{Int64,Int64}, loopchunksize::Dict{Any,Any}, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:278
 [14] #mapCube#34 at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:177 [inlined]
 [15] #mapslices#48 at /home/crem_fe/.julia/dev/YAXArrays/src/DAT/DAT.jl:217 [inlined]
 [16] top-level scope at ./timing.jl:174 [inlined]
 [17] top-level scope at ./REPL[11]:0
```

**Comment by meggart** [comment] 2020-09-03 07:15
I think a reproducer for this would be:

````julia
using Distributed

module A
using Distributed
function rc()
    remotecall_fetch(()->true, workers()[1])
end
end
addprocs(1)

A.rc()
````
The problem is that we use `remotecall` from module `A` here even if we don't invoke a function defined in `A`. If you find a way to make this work, that would be great, otherwise this might be a good question for the discourse forum.

**Comment by meggart** [comment] 2020-09-03 07:31
Ah and check out that this works:

````julia
using Distributed

module A
using Distributed
function rc()
    remotecall_fetch(sin, workers()[1], 1)
end
end
addprocs(1)

A.rc()
````

So it looks like the reason is that the anonymous function `()->true` is defined within the module `A`.

**Closed** 2022-02-01 08:54 UTC
